version: "3"

services:
    redis:
        image: redis:alpine
        container_name: bossabox-db-redis
        volumes:
            - redis-db-data:/data
        networks:
            - container-network
        ports:
            - "6379:6379"
    postgres:

        image: postgres:latest
        container_name: bossabox-db-postgres
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: bossabox
        volumes:
            - postgres-db-data:/data
        networks:
            - container-network
        ports:
            - "5432:5432"
    api:
        build: .
        command: sh -c "./wait-for.sh postgres:5432 -- yarn && yarn typeorm migration:run && yarn dev"
        depends_on:
            - postgres
            - redis
        container_name: bossabox-node-js-backend
        volumes:
            - .:/home/node/api
            - /home/node/api/node_modules
        ports:
            - "3000:3000"
            - "9229:9229" #debugger
        networks:
            - container-network

volumes:
    postgres-db-data:
    redis-db-data:

networks:
    container-network:
        driver: bridge